# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5GS0SCdTYLPSzvD0RKC1nnW2drjpvhS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Fitness_Classification.csv')
df

df.replace({'fuma':{'sí':1, 'no':0, 'Si':1,'No':0},
           'género':{'F':0,'M':1}}, inplace=True)

histo = sns.histplot(df['is_fit'], bins=2)

df.isnull().sum()

from sklearn.impute import KNNImputer
import pandas as pd

# Create a copy to avoid modifying the original DataFrame 'df' directly
df_processed = df.copy()

# Convert 'smokes' column to numerical values
df_processed['smokes'] = df_processed['smokes'].replace({'yes': 1, 'no': 0, '1': 1, '0': 0}).astype(int)

# Convert 'gender' column to numerical values
df_processed['gender'] = df_processed['gender'].replace({'F': 0, 'M': 1}).astype(int)

impKNN = KNNImputer(n_neighbors=10)
# Apply KNNImputer on the processed DataFrame
fitness = impKNN.fit_transform(df_processed)
fitness = pd.DataFrame(fitness, columns=df_processed.columns)
fitness

fitness.to_csv('Fitness2.csv', index=False)

from sklearn.model_selection import train_test_split


X = fitness.drop(columns='is_fit')
y = fitness['is_fit']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, stratify=y, random_state=1613808)

from sklearn.tree import DecisionTreeClassifier

dtree = DecisionTreeClassifier(criterion='entropy', max_depth=3, max_features=5, min_samples_leaf=25, random_state=1613808)
dtree.fit(X_train, y_train)


# METRICAS IDENTICAS
from sklearn.metrics import accuracy_score, f1_score, average_precision_score
from sklearn.metrics import classification_report, confusion_matrix


predictions = dtree.predict(X_test)
accuray_dt = accuracy_score(y_test, predictions)
f1_dt = f1_score(y_test, predictions)


print(f"Exactitud: {accuray_dt:0.2f}")
print(f"Valor F1: {f1_dt:0.2f}")
print(confusion_matrix(y_test, predictions))


# REGLAS DEL ARBOL IDENTICAS
from sklearn.tree import export_graphviz
import pydot
from six import StringIO
from sklearn.tree import _tree


features = list(X)
target = ['No','Sí']


def get_rules(tree, feature_names, class_names):
    tree_ = tree.tree_
    feature_name = [feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!" for i in tree_.feature]


    paths = []
    path = []


    def recurse(node, path, paths):
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            threshold = tree_.threshold[node]
            p1, p2 = list(path), list(path)
            p1 += [f"({name} <= {np.round(threshold,3)})"]
            recurse(tree_.children_left[node], p1, paths)
            p2 += [f"({name} > {np.round(threshold,3)})"]
            recurse(tree_.children_right[node], p2, paths)
        else:
            path += [(tree_.value[node], tree_.n_node_samples[node])]
            paths += [path]


    recurse(0, path, paths)


    samples_count = [p[-1][1] for p in paths]
    ii = list(np.argsort(samples_count))
    paths = [paths[i] for i in reversed(ii)]


    rules = []
    for path in paths:
        rule = "if "
        for p in path[:-1]:
            if rule != "if ":
                rule += " and "